### ISSUE TITLE
Issue with Missing Model Migrations in 'appointment' Application

### ISSUE THREAD

**Issue by OscarGonzalez97** [adamspd/django-appointment#132]
**Describe the bug**
When attempting to add the application to the project, the corresponding models are not being created.

**To Reproduce**
I follow [this](https://github.com/adamspd/django-appointment?tab=readme-ov-file#quick-start-) instructions.

**Expected behavior**
After adding the 'appointment' application and running migrations, the corresponding models should be created successfully.

**Screenshots**
I follow all the steps and my project doesn't run migrations of 'appointment' application:
<img width="1246" alt="image" src="https://github.com/adamspd/django-appointment/assets/36247829/dc545ec5-f96b-46f7-97c3-59f309d9e736">
And It's installed correctly
<img width="342" alt="image" src="https://github.com/adamspd/django-appointment/assets/36247829/65670a78-3acd-41e3-8e4d-667750916dba">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 105.0.5195.125
 
**Additional context**
The 'appointment' application is installed correctly, but the models are not being created.

## Possible Solution
-

## Can you fix the bug?
- [ ] Yes, I can fix the bug and will open a pull request.
- [X] No, I can't fix the bug, but I can assist in testing and providing feedback.
- [X] No, I can't fix the bug, but I can provide more information to help you fix it.
- [X] No, I can't fix the bug, but I can open an issue to report it.

**Comment by adamspd** [comment]
Hi @OscarGonzalez97, I just read the part of the documentation talking about this and I noted that I didn't say to run the command `python manage.py makemigrations` and I should've since the migrations are not included in the releases because by doing so, it would impact your database if the migrations I create on my machine are corrupted. 

Try to run the following command and I think it should solve the problem for you : 

```bash
python manage.py makemigrations appointment
```

This will create the migration files specific to django-appointment and then run 

```bash
python manage.py migrate
```

From there your issue should be solved.

Thanks for pointing that out, I will change to documentation to add the command.
Adams

**Comment by adamspd** [comment]
If this solves your problem, let me know and close the issue afterwards.

**Comment by OscarGonzalez97** [comment]
Excellent I ran that command and migrations were created 👍 Thank you!
