### ISSUE TITLE
Click login, but go no where

### ISSUE THREAD

**Issue by elcolie** [adamspd/django-appointment#238]
**Describe the bug**
When user try to make an appointment without login first. Then at appointment page click login, but no where to go

**To Reproduce**
1. Add service
2. Add staff
3. Click on proper time slot
4. Click login

**Expected behavior**
Website redirect to login page or register page for user.

**Screenshots**
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/d75299d9-683c-423a-ba23-3e4e420960be">

**Desktop (please complete the following information):**
 - OS: `FROM docker.io/python:3.12.5-slim-bookworm`
 - Browser Chrome

**Additional context**
`django==5.0.8`
`django-appointment==3.6.3`

## Possible Solution
No idea yet

## Can you fix the bug?
- [ ] Yes, I can fix the bug and will open a pull request.
- [ ] No, I can't fix the bug, but I can assist in testing and providing feedback.
- [ ] No, I can't fix the bug, but I can provide more information to help you fix it.
- [x] No, I can't fix the bug, but I can open an issue to report it.

**Comment by adamspd** [comment]
Hi @elcolie, 

This isn't working at the moment, so it's normal that nothing happens when you click on it. The implementation depends on how the project handles the login process with Django, so it might take me a bit of time to sort it out. However, if you're up for it, I'd be happy to review a pull request if you'd like to take a crack at it.

Adams
