### ISSUE TITLE
Finished appoinentrequest, but cannot create an appoinement

### ISSUE THREAD

**Issue by elcolie** [adamspd/django-appointment#239]
![image](https://github.com/user-attachments/assets/5b45ced7-a302-44b5-88dc-29edda89b429)
Finish button become disabled and `appointmentrequest` instance is created. But how to create the `appoinetment`?

I have watched youtube in the document, but it skipped the process of making `appointment`.

Question:
What to do next in order to create `appointment`?

**Comment by adamspd** [comment]
Hi @elcolie, I'm not entirely sure why it isn't working in your specific case, but it might be related to the type of characters being used. I tested the latest version of the project locally, and the results are shown below. Could you please try using Latin characters to see if that resolves the issue?

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/e79c2f16-0c30-407e-baef-0983b1f8a742">

**Comment by elcolie** [comment]
It is not related to character. I can click `Finish` button. But the problem is. After click I got `AppointmentRequest` instance in the database, but `Appointment` is not made.

**Comment by adamspd** [comment]
Oh, okay, I did not understand the issue then.
How so ?

You don't have any errors ? 
Can you provide screenshots ?

**Comment by adamspd** [comment]
Try running it with docker to see if you have the same behaviour.
It is described [here](https://github.com/adamspd/django-appointment?tab=readme-ov-file#docker-support-).

**Comment by elcolie** [comment]
@adamspd I got the same error. Even use your `Docker`.
After click `Finish`. I got `AppointmentRequest` created, but `Appointment` is not.

**Comment by elcolie** [comment]
@adamspd 
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/d2c5f33f-98d6-4732-95cc-cf3441e946b7">
Live Demo also stuck when I click `Finish` too.

**Comment by adamspd** [comment]
I'll look into it and try to figure out why, thank you for pointing that out.

**Comment by adamspd** [comment]
Hi @elcolie, after a few tests, I saw that the demo website is not working properly due to a django_q configuration issue. It gets the appointment and all, but once in the sending email steps, it slows down and encounters timeouts to finally show a 502 error. It also looks like some migrations aren't applied correctly by the automated script that restores the database every 2 hours. I've taken the site offline while I work on fixing this. There's a good chance the same problem could pop up when using the package in other projects if django_q isn't configured correctly (although it works with the settings in the project locally).
Once I've nailed down the exact cause and solution, I'll update both the documentation and this issue with all the details if needed.

**Comment by saritpop** [comment]
Why don't you try using `Celery`. You can follow the setup example from `Django CookieCutter`.

**Comment by elcolie** [comment]
Why don't you try using Celery. You can follow the setup example from Django CookieCutter.

**Comment by adamspd** [comment]
Hi @elcolie, I'd love to use it, but due to time and other requirements I won't be able to add this feature soon.

I finally found the problem with the [demo website](https://django-appt.adamspierredavid.com/), it was not because of the package, although I added a new feature in #253 where Django-Q is not a requirement any more (at least you don't have to install it if you're not using it). 
The problem was that I use an email server to send email when a user tries the demo so they can see what it looks like. The configuration on the server was replaced by my local configuration, thus, the timeout.

When you try the package locally, make sure that the settings in appointments/settings.py is correct ***for you***. Some of the configuration may cause the package to not work if your setup is different.

**Comment by adamspd** [comment]
Feel free to close this issue.

**Comment by adamspd** [comment]
I'm completely at a loss. I just tried the demo site, and it works fine as expected. I'd love to understand why it's not working for you. Email me at vhmnk@adamspierredavid.com, and we'll set something up quickly so I can have a look at your issue.

**Comment by adamspd** [comment]
Just to clarify, have you updated the [settings.py](https://github.com/adamspd/django-appointment/blob/main/appointments/settings.py) file to include the correct configuration for Docker Compose ? This step is essential for it to work properly. I realize this might not be immediately clear, so I'm considering adding a new PR with additional warnings and guidance for the correct configuration when using the project locally.

**Comment by elcolie** [comment]
@adamspd Thank you for your kindness. I have sent out my email which contains my video log to help you investigate my issue. I will close this issue when we found the root cause.

**Comment by elcolie** [comment]
Run it without `docker-compose` it works.
